# Generated by Django 2.2.1 on 2019-05-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ourdetails',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('collegename', models.TextField(max_length=200)),
                ('contactnumber', models.IntegerField()),
                ('emailId', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
